version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: pulsestream-redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr 0.0.0.0:33145
      - --advertise-rpc-addr 127.0.0.1:33145
    ports:
      - 19092:19092
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy'"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: pulsestream-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: pulsestream-qdrant
    ports:
      - 6333:6333
    volumes:
      - qdrant-data:/qdrant/storage

  ollama:
    image: ollama/ollama:latest
    container_name: pulsestream-ollama
    ports:
      - 11434:11434
    volumes:
      - ollama-data:/root/.ollama

  # --- NEW SERVICES ---
  
  producer:
    build: ./backend
    container_name: pulsestream-producer
    command: python producer.py
    environment:
      - PYTHONUNBUFFERED=1  
      - KAFKA_BROKER=redpanda:9092
    depends_on:
      redpanda:
        condition: service_healthy

  consumer:
    build: ./backend
    container_name: pulsestream-consumer
    command: python consumer.py
    environment:
      - PYTHONUNBUFFERED=1
      - KAFKA_BROKER=redpanda:9092
      - REDIS_HOST=redis
      - QDRANT_HOST=qdrant
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      redpanda:
        condition: service_healthy
      redis:
        condition: service_started
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
  bridge:
    build:
      context: ./frontend
      dockerfile: Dockerfile.bridge
    container_name: pulsestream-bridge
    ports:
      - "3001:3001"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_started
volumes:
  redpanda-data:
  redis-data:
  qdrant-data:
  ollama-data: